"""
Django settings for mb project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b#ly6v+18a5l-)r3!o6qzg6h3j))xsx#7-2_g%_gciwsim=2_#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['niyud.co.il', 'www.niyud.co.il', '64.176.165.149', 'rakesh4.niyud.co.il', '*.niyud.co.il']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'mb_core',
    'admin_manager'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'mb_core.middlewares.TenantMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mb',
        'USER': 'remote_user',
        'PASSWORD': 'CTx56yVjILREMLak8YKx',
        'HOST': '64.176.170.192',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # Optional for strict SQL mode
            'charset': 'utf8',
        },
    },
    'master': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mb',
        'USER': 'remote_user',
        'PASSWORD': 'CTx56yVjILREMLak8YKx',
        'HOST': '64.176.170.192',
        'PORT': '3306',                    # Default MySQL port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # Optional for strict SQL mode
            'charset': 'utf8',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'react', 'build', 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'http://mb.local'
# ]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
]

# AUTH_USER_MODEL = 'tenants.CustomUser'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=50),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',

    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

MASTER_DB_NAME = "mb"

MASTER_DB = DATABASES['master']

MASTER_DB_DSN = f"{MASTER_DB['ENGINE']}://{MASTER_DB['USER']}:{MASTER_DB['PASSWORD']}@{MASTER_DB['HOST']}:{MASTER_DB['PORT']}/{MASTER_DB['NAME']}"

SUPPORTED_LANGUAGES = ["en", "he"]

APP_DOMAIN = "niyud.co.il"

PLOI_API_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYTIyODM0ZTY1OTlhZjAwYmU1N2JjNGI4MTk2YjUzYTRiZjI1YmM5MGI2ZWZjZTM4NjkwYmZlZTBiN2RlNzBhZTQ1NGI5YmEwMWEyOTI5NTUiLCJpYXQiOjE3MzYzMzcwMDIuNDgyNjg4LCJuYmYiOjE3MzYzMzcwMDIuNDgyNjkxLCJleHAiOjE3OTk0MDkwMDIuNDc5NTY5LCJzdWIiOiIyOTc5NSIsInNjb3BlcyI6WyJzZXJ2ZXJzLXJlYWQiLCJzZXJ2ZXJzLWNyZWF0ZSIsInNlcnZlcnMtZGVsZXRlIiwiZGF0YWJhc2UtcmVhZCIsImRhdGFiYXNlLWNyZWF0ZSIsImRhdGFiYXNlLWRlbGV0ZSIsImRhZW1vbnMtcmVhZCIsImRhZW1vbnMtY3JlYXRlIiwiZGFlbW9ucy1kZWxldGUiLCJjcm9uam9icy1yZWFkIiwiY3JvbmpvYnMtY3JlYXRlIiwiY3JvbmpvYnMtZGVsZXRlIiwibmV0d29yay1ydWxlcy1yZWFkIiwibmV0d29yay1ydWxlcy1jcmVhdGUiLCJuZXR3b3JrLXJ1bGVzLWRlbGV0ZSIsInN5c3RlbS11c2Vycy1yZWFkIiwic3lzdGVtLXVzZXJzLWNyZWF0ZSIsInN5c3RlbS11c2Vycy1kZWxldGUiLCJzc2gta2V5cy1yZWFkIiwic3NoLWtleXMtY3JlYXRlIiwic3NoLWtleXMtZGVsZXRlIiwic2l0ZXMtcmVhZCIsInNpdGVzLWNyZWF0ZSIsInNpdGVzLWRlbGV0ZSIsInJlZGlyZWN0cy1yZWFkIiwicmVkaXJlY3RzLWNyZWF0ZSIsInJlZGlyZWN0cy1kZWxldGUiLCJjZXJ0aWZpY2F0ZXMtcmVhZCIsImNlcnRpZmljYXRlcy1jcmVhdGUiLCJjZXJ0aWZpY2F0ZXMtZGVsZXRlIiwiYXV0aC11c2Vycy1yZWFkIiwiYXV0aC11c2Vycy1jcmVhdGUiLCJhdXRoLXVzZXJzLWRlbGV0ZSIsImFsaWFzZXMtcmVhZCIsImFsaWFzZXMtY3JlYXRlIiwiYWxpYXNlcy1kZWxldGUiLCJlbWFpbCJdfQ.4VUyFfvhgBSw-LCSU-ovpkJQJAPkuWSPdGOMN5_xXhKcEieGt0GHNI7CbjXZfiMGVz2NlfkcPdtkWmXQG334ojjE9fNtw9t-99aMawWqdCkaa9yfMoz0mXa20LAcINke02A9mOMCDAVVilvGpnp3Tkkw3glQCBPFdTDZy6NzRHchVwTGBMs3AeTQ9lElrXsIisK4hr9el8C7XrL7PqhB3Cnrg20J_ZcTKyrOoFbO2OUB7LKSmz4jdSl97pgZcsWB6Fr7Xkb1ScC61imutwbHEl-wYepTacz9Y2558y2u1XhlyJxrFwuA2OllbP54wIskwvonJsH6ZIp5QctP8XYv1cAeeRoOP4S6vxY_styp3PiW7_z0sk9SsuLY9n5wzONd19H3xYPvfSHJne-LAmMAxMB4cqUzb4DAF4Wf7dHowT4uRa8443g3xSyFgZ5gEzwkL1_xUl6lJLWTw2TLVUsPs3tA_OiBWJx9hL-3tMOwXodueda1Z5YIhhq18h17_lsR5fS2L47URK_y_sJAiHMG0mJjKV72zFNVVimlwoVB3REkkBw3zYEb10ZutcO7ao3DiHNT0K4fbeVuHpLKQiZN2iAvePTdGS7at2gawqqG3LKTAd2zvuKEUiYFhvQ3p80EnCQJhXMg0ZEr5ayrdJA1Hc1uuvy9b_523pLnxVNf8hw"
