"""
Django settings for mb project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b#ly6v+18a5l-)r3!o6qzg6h3j))xsx#7-2_g%_gciwsim=2_#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['niyud.co.il', 'www.niyud.co.il', '64.176.165.149']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'mb_core',
    'admin_manager'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'mb_core.middlewares.TenantMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mb',
        'USER': 'remote_user',
        'PASSWORD': 'CTx56yVjILREMLak8YKx',
        'HOST': '64.176.170.192',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # Optional for strict SQL mode
            'charset': 'utf8',
        },
    },
    'master': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mb',
        'USER': 'remote_user',
        'PASSWORD': 'CTx56yVjILREMLak8YKx',
        'HOST': '64.176.170.192',
        'PORT': '3306',                    # Default MySQL port
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # Optional for strict SQL mode
            'charset': 'utf8',
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'react', 'build', 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'http://mb.local'
# ]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
]

# AUTH_USER_MODEL = 'tenants.CustomUser'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=50),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',

    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

MASTER_DB_NAME = "mb"

MASTER_DB = DATABASES['master']

MASTER_DB_DSN = f"{MASTER_DB['ENGINE']}://{MASTER_DB['USER']}:{MASTER_DB['PASSWORD']}@{MASTER_DB['HOST']}:{MASTER_DB['PORT']}/{MASTER_DB['NAME']}"

SUPPORTED_LANGUAGES = ["en", "he"]

APP_DOMAIN = "niyud.co.il"

PLOI_API_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMTEzMTNlN2I4YmVkMDk2MWU1YWM5ZmI5ZTU2OTVjODc4NzNiNGE5ZjdlNDU5NWFiMGU1YzJkZWJlOWM0OWY0ZmQ4Y2VlZWI0NGY4ZWI2OTkiLCJpYXQiOjE3MzYzMzY2MzEuMTk5MzYyLCJuYmYiOjE3MzYzMzY2MzEuMTk5MzY1LCJleHAiOjE3OTk0MDg2MzEuMTk3MjgxLCJzdWIiOiIyOTc5NSIsInNjb3BlcyI6WyJkYXRhYmFzZS1yZWFkIiwiZGF0YWJhc2UtY3JlYXRlIiwiZGF0YWJhc2UtZGVsZXRlIl19.bgrlvkzuAqMbsH1JkCigBtrxvtRmc4vKNCcaaXXl2qCJZPAjVmZ-5z1q69lCduu3LrZCd97UOHnqDGW_ywK_9wx5MAKTILSe1uK8eCsuwBRQ3PxbQWVreFvLHEjTaFP5fy_ywv7o8fjTOFy9sMTuRHKjhk1q_GXMol5WArvMQZhq1FFkMSD6zy9v8dniY_aik1p0Yd_8SnvDAlfLxwx2Vwghaw1tx3umddNQywwEiTvY6DhbCD4QKO40rkTQM6HdDy4eFivUal6KMz69rA2ZWAUfguwo_sBHWHPosUPxsP1oeE-PvvtXDwU3efyZVkwqWh8xC928pECocCH64M_61d-3j6lKFSGEtH0K1WkluQkEwZvAYp-4GgBSfgPlssT7ffGjRn84jpTEchDgQma52pRP5fCjGDaGzkn_sXBfJqVaX9ig5z0gQZ7hca2hf9YStIM2bWTUnALK_PWfz078ZoFr36IqI3FBJbzcOXQ4z7prNNpDULu9SpZ4ooVPFeBVErJqEj88Hiei316EncpIWh187aZlYN5j-NTzKkSqAj2fHhQBGx0uoHWfoOzIJ9fAMTm7U1exJf_w1H6zisj0xyXjcyndF-UlUJIupQ4rUnIx2IJ08pt6l85909h5BgUr-eR42dAPX-GMjiuVhQr3s3yK7p_tVrSDePpGLQe2Bfs"
