# Generated by Django 5.1.4 on 2025-01-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
