# Generated by Django 5.1.4 on 2025-01-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ULM', '0002_userprofile_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='slug',
            new_name='subdomain',
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='firstname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
