# Generated by Django 5.1.4 on 2025-01-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULM', '0003_rename_slug_tenant_subdomain_tenant_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tenant',
            table='tenants',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
