# Generated by Django 5.1.4 on 2025-01-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ULM', '0006_entity_entitycontenttype'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE auth_group DROP CONSTRAINT name;
            """,
            reverse_sql="""
            ALTER TABLE auth_group ADD CONSTRAINT name UNIQUE (name);
            """
        ),
    ]
