# Generated by Django 5.1.4 on 2025-01-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField(default=0)),
                ('entity', models.CharField(max_length=100)),
                ('entity_id', models.IntegerField(default=0)),
                ('firstname', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('name', models.CharField(max_length=100)),
                ('subdomain', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100, null=True, unique=True)),
                ('db_name', models.CharField(max_length=100, unique=True)),
                ('dsn', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('shared_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
            },
        ),
    ]
